[package]
name = "dl_client"
version = "0.1.1"
edition = "2021"
authors = ["Eric Skepz <skepz.dev@gmail.com>"]

[dependencies]
dl_network_common = { path = "../dl_network_common" }
better_term = "1.3.7"